from .BandejaSerializer import BandejaSerializer
from .CarreraSerializer import CarreraSerializer
from .CategoriaSerializer import CategoriaSerializer
from .EntradaSerializer import EntradaSerializer
from .TipoUsuarioSerializer import TipoUsuarioSerializer
from .UniversidadSerializer import UniversidadSerializer
from .UsuarioSerializer import UsuarioSerializer
from .ViviendaSerializer import ViviendaSerializer
